// Names of entries stored within the OS keychain:
let keychain_accountName_keychain = "securityFile_keychain"
let keychain_accountName_biometrics = "securityFile_biometrics"
let keychain_accountName_softBiometrics = "biometrics"
let keychain_accountName_passcodeFallback = "passcodeFallback"
let keychain_accountName_lockPin = "customPin"
let keychain_accountName_invalidLockPin = "invalidPin"
let keychain_accountName_bip353Address = "bip353Address"
let keychain_accountName_spendingPin = "spendingPin"
let keychain_accountName_invalidSpendingPin = "invalidSpendingPin"
