# Build a Phoenix apk for Testnet, using the master branch.
name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'phoenix-legacy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # 1 - checkout project and dependencies

    - name: Checkout Phoenix
      uses: actions/checkout@v2
      with:
        path: phoenix

    - name: Checkout eclair-core
      uses: actions/checkout@v2
      with:
        repository: ACINQ/eclair
        ref: android-phoenix
        path: eclair-core

    - name: Checkout Tor_Onion_Proxy_Library
      uses: actions/checkout@v2
      with:
        repository: ACINQ/Tor_Onion_Proxy_Library
        path: tor-lib

    # 2 - setup cache/jdk

    - name: Cache maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up jdk 1.11
      uses: actions/setup-java@v1
      with:
         java-version: 11

    # 3 - build dependencies & app

    - name: Build eclair-core and install to local maven repo
      run: |
        cd eclair-core
        mvn clean install -pl eclair-core -am -Dmaven.test.skip=true

    - name: Build Tor_Onion_Proxy_Library and install to local maven repo
      run: |
        cd tor-lib
        ./gradlew install
        ./gradlew :universal:build
        ./gradlew :android:build
        ./gradlew :android:publishToMaven

    - name: Assemble legacy app debug apk
      run: |
        cd phoenix
        ./gradlew clean
        printf "\nskip.android=false" >> local.properties
        ./gradlew :phoenix-legacy:assembleDebug --stacktrace
